Updated to work with NIST API 2.0
GamehunterKaan/AutoPWN-Suite pull request #48
Opened 2024-02-04 05:41 UTC by evillogic

NIST retired the 1.0 APIs that this project relied upon on Dec 18, 2023. This is causing the nist_search module to receive a 404 error for every keyword search and return no data. There are currently 2 issues #46 and #47 that this PR would fix, both the same root cause.

See the timeline of the API retirement [here](https://nvd.nist.gov/general/news/change-timeline)

The endpoint was changed from 1.0 to 2.0, the keyword parameter is now "keywordSearch" instead of "keyword", and the 2.0 API requires the API key in a header instead of a get parameter.

The response schema has also changed, so I had to update FindVulns to account for that as well.

2024-02-19 06:51 UTC, evillogic commented
@GamehunterKaan @eric-glb @iaacornus

Is this project still active?

2024-02-21 19:12 UTC, GamehunterKaan approved these changes

2024-02-21 19:29 UTC, GamehunterKaan requested changes

2024-02-21 19:29 UTC, GamehunterKaan commented on modules/nist_search.py
> +            data = response.json()
There still seems to be an issue with this variable.
![image](https://github.com/GamehunterKaan/AutoPWN-Suite/assets/68380968/4ec090d2-2029-4ee1-8440-6a5aa2831194)

2024-02-24 04:28 UTC, evillogic commented on modules/nist_search.py
> +            data = response.json()
I added some checks for that variable not existing, tested with `sudo python3 autopwn.py -t 158.174.109.227`

2024-02-24 04:31 UTC, evillogic commented on modules/nist_search.py
> +            data = response.json()
please re-review

2024-02-27 18:51 UTC, GamehunterKaan approved these changes

2024-02-27 18:54 UTC, merged

2024-02-27 18:54 UTC, GamehunterKaan commented
Fixed #46 & #47